#!/bin/sh
# change dir to project path
DIR="$(dirname "$0")"
cd $DIR

# create and activate virtualenv
python3 -m venv venv
source ./venv/bin/activate

# install dependencies
echo "Installing/updating dependencies..."
pip3 install --upgrade pip > /dev/null
pip3 install requests websupportsk > /dev/null

# start script
echo "websupportsk_ddns/websupportsk_ddns.py $1"
python3 websupportsk_ddns/websupportsk_ddns.py $1